export const EDITAR_FECHAS = 'EDITAR_FECHAS';
export const EDITAR_HORARIOS = 'EDITAR_HORARIOS';

export const AGREGAR_TURNO = 'AGREGAR_TURNO';
export const EDITAR_TURNO = 'EDITAR_TURNO';
export const ELIMINAR_TURNO = 'ELIMINAR_TURNO';

export const AGREGAR_PACIENTE = 'AGREGAR_PACIENTE';
export const EDITAR_PACIENTE = 'EDITAR_PACIENTE';
export const AGREGAR_ATENCION = 'AGREGAR_ATENCION';

export const AGREGAR_SERVICIO = 'AGREGAR_SERVICIO';
export const EDITAR_SERVICIO = 'EDITAR_SERVICIO';
export const ELIMINAR_SERVICIO = 'ELIMINAR_SERVICIO';
